# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArcBox.LinkCode
PackageVersion: 0.19.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
Protocols:
- linkcode
ProductCode: 8026af0d-384e-5456-9fd1-2393808153ee
ReleaseDate: 2026-08-02
AppsAndFeaturesEntries:
- DisplayName: LinkCode 0.19.0
  Publisher: ArcBox Labs
  ProductCode: 8026af0d-384e-5456-9fd1-2393808153ee
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/arcboxlabs/linkcode/releases/download/v0.19.0/LinkCode-0.19.0-x64.exe
  InstallerSha256: 5564FA977CC89D7356BD4EE31F9AE5E30E20A1C9AB5741FC6D771CEC0BAFE227
- Architecture: arm64
  InstallerUrl: https://github.com/arcboxlabs/linkcode/releases/download/v0.19.0/LinkCode-0.19.0-arm64.exe
  InstallerSha256: 7DF18723325CEEDB9985631F3666F26C0A6F97DC30E59AD1B7C6E5BE6AEA405F
ManifestType: installer
ManifestVersion: 1.12.0
