# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ArcBox.LinkCode
PackageVersion: 0.11.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
Protocols:
- linkcode
ProductCode: 8026af0d-384e-5456-9fd1-2393808153ee
ReleaseDate: 2026-07-30
AppsAndFeaturesEntries:
- DisplayName: LinkCode 0.11.0
  Publisher: ArcBox Labs
  ProductCode: 8026af0d-384e-5456-9fd1-2393808153ee
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/arcboxlabs/linkcode/releases/download/v0.11.0/LinkCode-0.11.0-x64.exe
  InstallerSha256: 1919C7BBB831A8CBE512B2358136E52DFC3CCE759905B53F0117162978F18736
- Architecture: arm64
  InstallerUrl: https://github.com/arcboxlabs/linkcode/releases/download/v0.11.0/LinkCode-0.11.0-arm64.exe
  InstallerSha256: 785D1B9E4CFEB6A81EA54ABE4040937AEC2850C4B68F5DE8123474E9C503728B
ManifestType: installer
ManifestVersion: 1.12.0
